name: publish-gh-pages
run-name: Publish on GitHub Pages

on:
  push:
    branches:
    - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - run: npm ci
    - run: npm run build-cv-tex
    - uses: xu-cheng/latex-action@v3
      with:
        root_file: MahmudAzam.tex
        working_directory: cv-pdf
    - run: mv cv-pdf/*.pdf public
    - run: npm run build
    - name: Package static files to deploy
      uses: actions/upload-pages-artifact@v3.0.0
      with:
        path: build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@main
